### ISSUE TITLE
Slow loading of images

### ISSUE THREAD

**Issue by saamerm** [saamerm/SMC-Website#2]
As you can see from this link, the website is slow and has some issues and a low score
https://pagespeed.web.dev/analysis/https-stairmasterclimber-com/8h1kers1aw?form_factor=mobile

Mainly because of a large image size:
<img width="988" alt="image" src="https://github.com/saamerm/SMC-Website/assets/8262287/1e0ac88a-1e69-4137-8369-b6d865be24e1">

But there also other issues that could be solved

**Comment by hnucxr** [comment]
fixed.
